### ISSUE TITLE
web3.storage: Space has no storage provider\n

### ISSUE THREAD

**Issue by talentlessguy** [FlashWeb3/flash-cli#8]
Logs:

```
╭─v1rtl@Asus in repo: flash-cli/examples/next
[🔴] × flash
Detected framework: Next.js
Deploying on IPFS 🌍Storage provider: estuary.tech 🛰
Uploading 1.5MB
file:///home/v1rtl/Coding/flash/flash-cli/node_modules/.pnpm/@web3-storage+upload-client@9.0.1/node_modules/@web3-storage/upload-client/src/store.js:78
throw new Error(`failed ${StoreCapabilities.add.can} invocation`, {
^

Error: failed store/add invocation
at add (file:///home/v1rtl/Coding/flash/flash-cli/node_modules/.pnpm/@web3-storage+upload-client@9.0.1/node_modules/@web3-storage/upload-client/src/store.js:78:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async queue.add.signal (file:///home/v1rtl/Coding/flash/flash-cli/node_modules/.pnpm/@web3-storage+upload-client@9.0.1/node_modules/@web3-storage/upload-client/src/sharding.js:98:29)
at async file:///home/v1rtl/Coding/flash/flash-cli/node_modules/.pnpm/p-queue@7.3.4/node_modules/p-queue/dist/index.js:118:36 {
[cause]: {
name: 'Error',
stack: 'Error: Space has no storage provider\n' +
'    at Object.allocateSpace (/upload-api/access.js:40:22)\n' +
'    at runMicrotasks (<anonymous>)\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
'    at async Promise.all (index 0)\n' +
'    at <anonymous> (/node_modules/@web3-storage/upload-api/src/store/add.js:19:58)\n' +
'    at invoke2 (/node_modules/@ucanto/server/src/server.js:139:22)\n' +
'    at async Promise.all (index 0)\n' +
'    at execute (/node_modules/@ucanto/server/src/server.js:98:5)\n' +
'    at ucanInvocationRouter (/upload-api/functions/ucan-invocation-router.js:168:20)\n' +
'    at Runtime.handler (/node_modules/src/awslambda.ts:339:1)',
message: 'Space has no storage provider'
}
}
```

**Comment by talentlessguy** [comment]
Reinitializing flash globally worked
